package com.kssidll.arrugarq.presentation.theme.schema

import androidx.compose.material3.*
import androidx.compose.ui.graphics.*

val DarkColorScheme = darkColorScheme(
    primary = Color(0xFF23242A),
    onPrimary = Color(0xFFE3E2E6),
    primaryContainer = Color(0xFF5D3A62),
    onPrimaryContainer = Color(0xFFFED6FF),
    //inversePrimary = Color(),
    secondary = Color(0xFFCCC2DC),
    onSecondary = Color(0xFF332D41),
    //secondaryContainer = Color(),
    //onSecondaryContainer = Color(),
    tertiary = Color(0xFFCBA6F7),
    onTertiary = Color(0xFF492435),
    tertiaryContainer = Color(0xFF633A48),
    onTertiaryContainer = Color(0xFFFFD8E3),
    background = Color(0xFF1B1B1F),
    onBackground = Color(0xFFE3E2E6),
    surface = Color(0xFF11131B),
    onSurface = Color(0xFFE3E2E6),
    //surfaceVariant = Color(),
    //onSurfaceVariant = Color(),
    //surfaceTint = Color(),
    //inverseSurface = Color(),
    //inverseOnSurface = Color(),
    error = Color(0xFFF2B8B5),
    onError = Color(0xFF601410),
    errorContainer = Color(0xFF8C1D18),
    onErrorContainer = Color(0xFFF9DEDC),
    outline = Color(0xFF938F99),
    //outlineVariant = Color(),
    scrim = Color(0xFFFFFFFF),
    //surfaceBright = Color(),
    surfaceContainer = Color(0xFF1E1F27),
    //surfaceContainerHigh = Color(),
    //surfaceContainerHighest = Color(),
    //surfaceContainerLow = Color(),
    //surfaceContainerLowest = Color(),
    //surfaceDim = Color(),
)
