package com.kssidll.arrugarq.presentation.theme.schema

import androidx.compose.material3.*
import androidx.compose.ui.graphics.*

val LightColorScheme = lightColorScheme(
    primary = Color(0xFF495D92),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDAE2FF),
    onPrimaryContainer = Color(0xFF001849),
    //inversePrimary = Color(),
    secondary = Color(0xFF625B71),
    onSecondary = Color(0xFFFFFFFF),
    //secondaryContainer = Color(),
    //onSecondaryContainer = Color(),
    tertiary = Color(0xFFCBA6F7),
    //onTertiary = Color(),
    //tertiaryContainer = Color(),
    //onTertiaryContainer = Color(),
    background = Color(0xFFFEFBFF),
    onBackground = Color(0xFF1B1B1F),
    surface = Color(0xFFF7F9FF),
    onSurface = Color(0xFF1B1B1F),
    //surfaceVariant = Color(),
    //onSurfaceVariant = Color(),
    //surfaceTint = Color(),
    //inverseSurface = Color(),
    //inverseOnSurface = Color(),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
    outline = Color(0xFF79747E),
    //outlineVariant = Color(),
    scrim = Color(0xFF000000),
    //surfaceBright = Color(),
    surfaceContainer = Color(0xFFEBEEF8),
    //surfaceContainerHigh = Color(),
    //surfaceContainerHighest = Color(),
    //surfaceContainerLow = Color(),
    //surfaceContainerLowest = Color(),
    //surfaceDim = Color(),
)
