[versions]
## Libraries
# AndroidX
activity-compose = "1.8.0"
core-splashscreen = "1.0.1"
appcompat = "1.7.0-alpha03"
datastore-preferences = "1.1.0-alpha06"
lifecycle-viewmodel-compose = "2.6.2"
accompanist-systemuicontroller = "0.32.0"

# Navigation
reimagined = "1.5.0"

# Compose
compose-ui = "1.6.0-alpha07"
material3 = "1.2.0-alpha09"
material = "1.6.0-alpha07"

# DI
hilt = "2.48"

# Room
room = "2.6.0"

# Other
fuzzywuzzy = "1.4.0"
vico-compose = "1.12.0"

## Plugins
agp = "8.3.0-alpha14"
kotlin = "1.9.10"
# hilt plugin has same version as hilt library so it is declared in the library section
ksp = "1.9.10-1.0.13"

[libraries]
# AndroidX
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-android", version.ref = "datastore-preferences" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }

# Navigation
reimagined = { group = "dev.olshevski.navigation", name = "reimagined", version.ref = "reimagined" }
reimagined-hilt = { group = "dev.olshevski.navigation", name = "reimagined-hilt", version.ref = "reimagined" }

# Compose
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose-ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose-ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose-ui" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose-ui" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-window-sizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material" }

# DI
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Room
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Other
fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico-compose" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico-compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
devtoolsKSP = { id = "com.google.devtools.ksp", version.ref = "ksp" }
