[versions]
## Libraries
# AndroidX
androidx-activity = "1.9.0"
androidx-splashscreen-core = "1.0.1"
androidx-appcompat = "1.7.0"
androidx-datastore-preferences = "1.1.1"

# Navigation
dev-navigation-reimagined = "1.5.0"

# Compose
androidx-compose-bom = "2024.06.00"

# DI
google-hilt = "2.48"

# Room
androidx-room = "2.6.1"

# Paging
androidx-paging = "3.3.0"

# Text fuzzy search
dev-text-search-fuzzywuzzy = "1.4.0"

# Chart
dev-chart-vico-compose = "1.14.0"

## Plugins
agp = "8.5.1"
kotlin = "1.9.22"
# hilt plugin has same version as hilt library so it is declared in the library section
ksp = "1.9.22-1.0.17"

[libraries]
# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
androidx-splashscreen-core = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences-android", version.ref = "androidx-datastore-preferences" }

# Navigation
dev-navigation-reimagined = { group = "dev.olshevski.navigation", name = "reimagined", version.ref = "dev-navigation-reimagined" }
dev-navigation-reimagined-hilt = { group = "dev.olshevski.navigation", name = "reimagined-hilt", version.ref = "dev-navigation-reimagined" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window-sizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# DI
google-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "google-hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "google-hilt" }

# Room
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }

# Paging
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "androidx-paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }

# Text
dev-text-search-fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "dev-text-search-fuzzywuzzy" }

# chart
dev-chart-vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "dev-chart-vico-compose" }
dev-chart-vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "dev-chart-vico-compose" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
devtoolsKSP = { id = "com.google.devtools.ksp", version.ref = "ksp" }
